import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { twMerge } from "tailwind-merge";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const firaCode = localFont({
  src: [
    {
      path: "./fonts/FiraCode-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/FiraCode-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/FiraCode-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/FiraCode-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/FiraCode-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-fira-code",
});

const molotFont = localFont({
  src: [
    {
      path: "./fonts/Molot.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-molot",
});

export const metadata: Metadata = {
  title: "Meu portifólio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-Br"
      className={twMerge(
        geistSans.variable,
        geistMono.variable,
        firaCode.variable,
        molotFont.variable,
        `h-full antialiased`,
      )}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="data-theme"
          defaultTheme="dark-theme"
          enableSystem={true}
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
